# Generated by Django 3.0.1 on 2020-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=30)),
                ('book_title', models.CharField(max_length=60)),
                ('list_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
