# Generated by Django 3.0.1 on 2020-03-16 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='list_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
