# Generated by Django 3.0.1 on 2020-03-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0002_auto_20200316_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookList',
            new_name='Books',
        ),
    ]
