# Generated by Django 3.0.1 on 2020-03-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0004_auto_20200318_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_title',
        ),
        migrations.AddField(
            model_name='books',
            name='book_title_or_author_name',
            field=models.CharField(default='what do you wanna read', max_length=100),
        ),
    ]
