# Generated by Django 2.2.7 on 2020-04-04 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0005_auto_20200318_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='what do you wanna hear', max_length=100)),
                ('list_pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
