# Generated by Django 2.2.7 on 2020-04-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0006_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Musics',
        ),
    ]
