# Generated by Django 2.2.7 on 2020-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0009_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(default='This book is about.....', max_length=1000),
        ),
    ]
