# Generated by Django 2.2.7 on 2020-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0013_auto_20200412_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_title_or_author_name',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='books',
            name='book_title',
            field=models.CharField(default='what do you wanna read', max_length=100),
        ),
    ]
